### ISSUE TITLE
Update package to use new forked location

### ISSUE THREAD

**Issue by jack-pappas** [conda-forge/frozendict-feedstock#6]
The ``python-frozendict`` package was forked due to the original maintainer abandoning the project. Control of the PyPI packages has been transferred to a new maintainer: https://github.com/slezica/python-frozendict/issues/25

The new maintainer @Marco-Sulla has made a number of improvements and updates. Can someone point this package feedstock to the new location so the conda package stays current with the new PyPI releases? The new fork resides here: https://github.com/Marco-Sulla/python-frozendict

**Comment by ltalirz** [comment]
thanks for the heads up - would you mind making a PR to fix this?
